# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/src"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🔗 :: "
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: "org.jetbrains.kotlin"
      - dependency-name: "com.android.tools.build"
    labels:
      - "빌드"
