[versions]
androidx-junit = "1.2.1"
androidx-espresso-core = "3.6.1"
androidx-compose-bom = "2024.09.01"
androidx-navigation-compose = "2.8.0"
anrwatchdog = "1.4.0"
coil-compose = "2.6.0"
androidx-compose-foundation = "1.7.1"
androidx-lifecycle-viewmodel = "2.8.5"

compose-stable-marker = "1.0.5"
converter-moshi = "2.9.0"
google-service = "4.4.2"
google-firebase-bom = "32.7.4"

firebase-messaging = "23.4.1"

hilt-android-gradle-plugin = "2.51.1"
junit = "4.13.2"
android-gradle = "8.2.2"
kotlin = "1.9.21"
kotlinx-collections-immutable = "0.3.7"
lottie-compose = "6.3.0"
moshi-kotlin = "1.15.1"
play-publisher = "3.8.4"
squareup-retrofit = "2.11.0"
squareup-logging-interceptor = "4.12.0"
squareup-javapoet = "1.13.0"
hilt-android-navigation = "1.2.0"
androidx-compose-material = "1.7.1"

com-google-android-material = "1.12.0"

kotlinx-serialization-json = "1.6.3"
org-jlleitschuh-ktlint-gradle = "11.3.1"

app-update-ktx = "2.1.0"

androidx-compose-ui-test = "1.7.1"
androidx-test-runner = "1.6.2"

androidx-room-runtime = "2.6.1"
junit-ktx = "1.2.1"

firebase-crashlytics = "2.9.9"

triplet-play = "3.8.4"

kotlin-ksp = "1.9.21-1.0.16"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.2.4"
baselineprofile = "1.2.4"
profileinstaller = "1.3.1"

[libraries]
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose" }
anrwatchdog = { module = "com.github.anrwatchdog:anrwatchdog", version.ref = "anrwatchdog" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }

com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material" }

androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle-viewmodel" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }

compose-stable-marker = { module = "com.github.skydoves:compose-stable-marker", version.ref = "compose-stable-marker" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebase-crashlytics" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android-gradle-plugin" }
junit = { module = "junit:junit", version.ref = "junit" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie-compose" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-android-gradle-plugin" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android-gradle-plugin" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-android-navigation" }

moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
play-publisher = { module = "com.github.triplet.gradle:play-publisher", version.ref = "play-publisher" }
squareup-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "squareup-retrofit" }
squareup-javapoet = { group = "com.squareup", name = "javapoet", version.ref = "squareup-javapoet" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "squareup-logging-interceptor" }

kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "google-firebase-bom" }
com-google-android-play = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update-ktx" }

firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging" }

androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidx-compose-ui-test" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt-android-gradle-plugin" }
androidx-compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "androidx-compose-foundation" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room-runtime" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room-runtime" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junit-ktx" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android-gradle-plugin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlinx-serialization = { id = "kotlinx-serialization", version.ref = "kotlin" }
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "org-jlleitschuh-ktlint-gradle" }
google-service = { id = "com.google.gms.google-services", version.ref = "google-service" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
triplet-play = { id = "com.github.triplet.play", version.ref = "triplet-play" }
android-test = { id = "com.android.test", version.ref = "android-gradle" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
