package team.retum.common.enums

enum class AlarmType {
    RECRUITMENT_STATUS_CHANGED,
    NEW_APPLICATION,
    APPLICATION_STATUS_CHANGED,
    INTERVIEW_SOON,
    NEW_RECRUITMENT,
    RECRUITMENT_DONE,
}
