name: Android CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [lint, build]

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Create google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/JOBIS-ANDROID-V2/JOBIS-ANDROID-V2/app/google-services.json

      - name: Execute Gradle task
        run: |
          if [ "${{ matrix.task }}" == "lint" ]; then
            ./gradlew ktlintCheck
          elif [ "${{ matrix.task }}" == "build" ]; then
            ./gradlew build
          fi
