name: Android CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Create local.properties
        run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decrypt google-services.json
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > $GITHUB_WORKSPACE/app/google-services.json

      - name: Check Ktlint
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew build
