name: Android CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches: 
      - develop
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle
    - name: Create local.properties
      run: echo '${{ secrets.LOCAL_PROPERTIES }}' > ./local.properties
    - name: Create google services file
      run: cat /home/runner/work/<Project-Name>/<Project-Name>/app/google-services.json | base64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Check Ktlint
      run: ./gradlew ktlintCheck
